### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by matteosavio** [fredl99/YOURLS-Upload-and-Shorten#22] opened 2023-06-13 14:44 UTC
It seems like this plugin only works with PHP up to 7.4, as soon as I switch to 8.2 or 8.3 the file upload doesn't result in anything. I'll try to look into it at some point.

**Comment by fredl99** [comment] 2023-06-15 23:11
Thank you for your comment! I'm sorry, I can't reproduce the problem. 
I'm using 8.0, but switched to 8.2 for a quick test. Both work as intended. 
I don't have 8.3 available for testing right now, but I wouldn't expect a big difference.
What's your YOURLS version? Maybe any other plugin is interferring?

**Comment by fredl99** [comment] 2024-01-05 16:04
@matteosavio  Could you find out anything about the issue or solve it?
If it's solved I'd like to close the case. Otherwise I'm ready to help.

**Comment by fredl99** [comment] 2024-04-20 15:16
As it seems to be solved and I still can't reproduce the problem even in PHP 8.3 I'll be closing here.

**Closed as completed** 2024-04-20 15:17 UTC
